2023-09-12 16:36:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "ANONASC" not found; SQL statement:
INSERT INTO cliente (nome, anoNasc, sexo, id_especie, id_tratamento, id_cliente) VALUES (?,?,?,?,?) [42122-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.table.Table.getColumn(Table.java:740)
	at org.h2.command.Parser.parseColumn(Parser.java:1644)
	at org.h2.command.Parser.parseColumnList(Parser.java:1629)
	at org.h2.command.Parser.parseInsert(Parser.java:1962)
	at org.h2.command.Parser.parsePrepared(Parser.java:1191)
	at org.h2.command.Parser.parse(Parser.java:1068)
	at org.h2.command.Parser.parse(Parser.java:1037)
	at org.h2.command.Parser.prepareCommand(Parser.java:965)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:624)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:562)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1111)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:283)
	at Model.AnimalDAO.create(AnimalDAO.java:32)
	at View.Main.main(Main.java:35)
2023-09-12 16:36:44 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "anoNasc" not found [42122-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3491)
	at org.h2.jdbc.JdbcResultSet.getInt(JdbcResultSet.java:336)
	at Model.AnimalDAO.buildObject(AnimalDAO.java:50)
	at Model.AnimalDAO.retrieve(AnimalDAO.java:63)
	at Model.AnimalDAO.retrieveAll(AnimalDAO.java:73)
	at View.Main.main(Main.java:38)
2023-09-12 16:42:06 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column count does not match; SQL statement:
INSERT INTO animal (nome, anoNasc, sexo, id_especie, id_tratamento, id_cliente) VALUES (?,?,?,?,?) [21002-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.message.DbException.get(DbException.java:192)
	at org.h2.command.dml.Insert.prepare(Insert.java:295)
	at org.h2.command.Parser.prepareCommand(Parser.java:971)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:624)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:562)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1111)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:283)
	at Model.AnimalDAO.create(AnimalDAO.java:32)
	at View.Main.main(Main.java:35)
2023-11-29 17:37:23 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "nome" not found [42122-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3517)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:300)
	at Model.ClienteDAO.buildObject(ClienteDAO.java:49)
	at Model.ClienteDAO.retrieve(ClienteDAO.java:62)
	at Model.ClienteDAO.retrieveAll(ClienteDAO.java:72)
	at View.Main.main(Main.java:35)
2023-11-29 17:37:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "nome" not found [42122-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3517)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:300)
	at Model.ClienteDAO.buildObject(ClienteDAO.java:49)
	at Model.ClienteDAO.retrieve(ClienteDAO.java:62)
	at Model.ClienteDAO.retrieveAll(ClienteDAO.java:72)
	at View.Main.main(Main.java:35)
2023-11-29 17:37:52 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "nome" not found [42122-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3517)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:300)
	at Model.ClienteDAO.buildObject(ClienteDAO.java:49)
	at Model.ClienteDAO.retrieve(ClienteDAO.java:62)
	at Model.ClienteDAO.retrieveAll(ClienteDAO.java:72)
	at View.Main.main(Main.java:35)
2023-11-29 17:40:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "nome" not found [42122-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3517)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:300)
	at Model.ClienteDAO.buildObject(ClienteDAO.java:49)
	at Model.ClienteDAO.retrieve(ClienteDAO.java:62)
	at Model.ClienteDAO.retrieveAll(ClienteDAO.java:72)
	at View.Main.main(Main.java:35)
2023-11-29 17:40:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "nome" not found [42122-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.jdbc.JdbcResultSet.getColumnIndex(JdbcResultSet.java:3517)
	at org.h2.jdbc.JdbcResultSet.getString(JdbcResultSet.java:300)
	at Model.ClienteDAO.buildObject(ClienteDAO.java:49)
	at Model.ClienteDAO.retrieve(ClienteDAO.java:62)
	at Model.ClienteDAO.retrieveAll(ClienteDAO.java:72)
	at View.Main.main(Main.java:35)
2023-11-30 14:01:50 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/ginoc/OneDrive/Documentos/GitHub/ClinicaVeterinaria/ClinicaVeterinaria.db.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
	at Model.DAO.getConnection(DAO.java:22)
	at Model.ClienteDAO.<init>(ClienteDAO.java:19)
	at Model.ClienteDAO.getInstance(ClienteDAO.java:25)
	at Controller.Controller.jRadioButtonClientesSelecionado(Controller.java:32)
	at View.Principal.clearComponents(Principal.java:31)
	at View.Principal.<init>(Principal.java:39)
	at View.Principal$11.run(Principal.java:397)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/ginoc/OneDrive/Documentos/GitHub/ClinicaVeterinaria/ClinicaVeterinaria.db.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 37 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/ginoc/OneDrive/Documentos/GitHub/ClinicaVeterinaria/ClinicaVeterinaria.db.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 31 more
2023-11-30 14:01:50 database: flush
org.h2.message.DbException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/ginoc/OneDrive/Documentos/GitHub/ClinicaVeterinaria/ClinicaVeterinaria.db.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.get(DbException.java:216)
	at org.h2.message.DbException.convert(DbException.java:414)
	at org.h2.mvstore.db.Store.lambda$new$0(Store.java:120)
	at org.h2.mvstore.MVStore.handleException(MVStore.java:3292)
	at org.h2.mvstore.MVStore.panic(MVStore.java:585)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:461)
	at org.h2.mvstore.MVStore$Builder.open(MVStore.java:4052)
	at org.h2.mvstore.db.Store.<init>(Store.java:129)
	at org.h2.engine.Database.<init>(Database.java:324)
	at org.h2.engine.Engine.openSession(Engine.java:92)
	at org.h2.engine.Engine.openSession(Engine.java:222)
	at org.h2.engine.Engine.createSession(Engine.java:201)
	at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:117)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:253)
	at Model.DAO.getConnection(DAO.java:22)
	at Model.DAO.createTable(DAO.java:79)
	at Model.ClienteDAO.<init>(ClienteDAO.java:20)
	at Model.ClienteDAO.getInstance(ClienteDAO.java:25)
	at Controller.Controller.jRadioButtonClientesSelecionado(Controller.java:32)
	at View.Principal.clearComponents(Principal.java:31)
	at View.Principal.<init>(Principal.java:39)
	at View.Principal$11.run(Principal.java:397)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "org.h2.mvstore.MVStoreException: The file is locked: C:/Users/ginoc/OneDrive/Documentos/GitHub/ClinicaVeterinaria/ClinicaVeterinaria.db.mv.db [2.0.206/7]" [50000-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:573)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	... 38 more
Caused by: org.h2.mvstore.MVStoreException: The file is locked: C:/Users/ginoc/OneDrive/Documentos/GitHub/ClinicaVeterinaria/ClinicaVeterinaria.db.mv.db [2.0.206/7]
	at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:1004)
	at org.h2.mvstore.FileStore.open(FileStore.java:163)
	at org.h2.mvstore.MVStore.<init>(MVStore.java:444)
	... 32 more
